### PR TITLE
Update dev gems + check of Railties + Field for errors

### PR DESCRIPTION
**Pull request by le0pard**
Update dev gems + check of Railties + add field for errors (this field helpfull for serach all errors in logs)

### CODE REVIEW

**Comment by astupka** [comment]
I will check it out. Thanks.  Were you able to run the tests against your commits?

Alex

**Comment by le0pard** [comment]
central_logger leo$ rake
(in /Users/leo/programs/projects/central_logger)
/Users/leo/.rvm/rubies/ruby-1.9.2-p180/bin/ruby -I"lib:lib:test" "/Users/leo/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake/rake_test_loader.rb" "test/unit/central_logger_test.rb" 
Loaded suite /Users/leo/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake/rake_test_loader
Started
......................
Finished in 3.035225 seconds.

22 tests, 26 assertions, 0 failures, 0 errors, 0 skips

Test run options: --seed 54317

**Comment by le0pard** [comment]
All done (also add test for field)

$ test/test.sh 

-----------Running tests for '1.8.7@central_logger'------------
(in /home/leo/programs/projects3/central_logger)
/home/leo/.rvm/rubies/ruby-1.8.7-p334/bin/ruby -I"lib:lib:test" "/home/leo/.rvm/gems/ruby-1.8.7-p334@global/gems/rake-0.8.7/lib/rake/rake_test_loader.rb" "test/unit/central_logger_test.rb" 
Loaded suite /home/leo/.rvm/gems/ruby-1.8.7-p334@global/gems/rake-0.8.7/lib/rake/rake_test_loader
Started
......................
Finished in 0.236735 seconds.

22 tests, 27 assertions, 0 failures, 0 errors

-----------Running tests for '1.8.7@central_logger_2'------------
(in /home/leo/programs/projects3/central_logger/test/rails/2)
/home/leo/.rvm/rubies/ruby-1.8.7-p334/bin/ruby -I"lib:test" "/home/leo/.rvm/gems/ruby-1.8.7-p334@global/gems/rake-0.8.7/lib/rake/rake_test_loader.rb"  

-----------Running tests for '1.8.7@central_logger_3'------------
(in /home/leo/programs/projects3/central_logger/test/rails/3)
Could not load SystemTimer >= v1.2.0. Falling back to timeout.rb. SystemTimer is STRONGLY recommended for timeouts in Ruby 1.8.7. See http://ph7spot.com/blog/system-timer-1-2-release for details.

-----------Running tests for '1.9.2@central_logger'------------
(in /home/leo/programs/projects3/central_logger)
/home/leo/.rvm/rubies/ruby-1.9.2-p180/bin/ruby -I"lib:lib:test" "/home/leo/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake/rake_test_loader.rb" "test/unit/central_logger_test.rb" 
Loaded suite /home/leo/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake/rake_test_loader
Started
......................
Finished in 0.116406 seconds.

22 tests, 27 assertions, 0 failures, 0 errors, 0 skips

Test run options: --seed 5887

-----------Running tests for '1.9.2@central_logger_2'------------
(in /home/leo/programs/projects3/central_logger/test/rails/2)
/home/leo/.rvm/rubies/ruby-1.9.2-p180/bin/ruby -I"lib:test" "/home/leo/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake/rake_test_loader.rb"  

-----------Running tests for '1.9.2@central_logger_3'------------
(in /home/leo/programs/projects3/central_logger/test/rails/3)

**Comment by le0pard** [comment]
What about my pull request?

**Comment by chmurph2** [comment]
Alex has been on vacation.  I'll ask him about this when he gets back.  Sorry about the delay.

**Comment by astupka** [comment]
Thanks for the pull request!

I merged the railtie check (04d2870).  I will push the commits once I figure out why the functional tests are failing.

Alex

**Comment by le0pard** [comment]
But I check tests - all pass. I just add boolean field for errors (is_exception) + test for this. Thats all. I think search by this field more simple to find errors, than use regex (like shown in README).

**Pull request closed without merging**
